
package ModulComponent;
import Product_Component.ProductModul;
import Logic.CurrentStock;
import Logic.product;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


public class CurrentStockModul extends javax.swing.JPanel {
    private static final String url = "jdbc:postgresql://localhost:5432/Inventory"; // Replace with your DB details
    private static final String user = "postgres"; // Replace with your DB username
    private static final String password = "dan@12345"; // Replace with your DB password
 
    public CurrentStockModul() {
        initComponents();
        showProductInTabel();
        JTableHeader header = jTable_currentSotck.getTableHeader();

        // Create the desired font for the header
        Font headerFont = new Font("Century Gothic", Font.BOLD, 18); // Example: Bold, Size 14
        header.setFont(headerFont);
    }
    // function that return an array list
    public ArrayList<CurrentStock> getcurrentStock()
    {
        ArrayList<CurrentStock> currenetStock = new ArrayList<>();
        try(Connection connection = DriverManager.getConnection(url, user, password)) {
            String query = "SELECT pr.id,pr.name,pr.category,pr.quantity as stockIN,ii.quantity as stockOut,pr.quantity - ii.quantity as currentStock "
                    + "FROM products pr INNER "
                    + "JOIN invoice_items ii  ON pr.id = ii.item_id ORDER BY pr.id ASC;";
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(query);
        
            while (rs.next()) {                
                Integer id = rs.getInt("id");
                String name = rs.getString("name");
                String category = rs.getString("category");
                Integer stockIn = rs.getInt("stockIn");
                Integer stockOut = rs.getInt("stockOut");
                Integer currentStock = rs.getInt("stockOut");
                currenetStock.add(new CurrentStock(id,name,category,stockIn,stockOut,currentStock));
                
            }
            
        } catch (Exception e) {
            Logger.getLogger(ProductModul.class.getName()).log(Level.SEVERE, null, e);
        }
        return currenetStock;
    }
    // function show product in table
    public void showProductInTabel()
    {
        ArrayList<CurrentStock> currenetStock = getcurrentStock();
        DefaultTableModel model = (DefaultTableModel) jTable_currentSotck.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        
        for( int i = 0;i < currenetStock.size();i++)
        {
            row[0] = currenetStock.get(i).getId();
            row[1] = currenetStock.get(i).getName();
            row[2] = currenetStock.get(i).getCategory();
            row[3] = currenetStock.get(i).getStockIn();
            row[4] = currenetStock.get(i).getStockOut();
            row[5] = currenetStock.get(i).getCurrentStock();
            
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_currentSotck = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable_currentSotck.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTable_currentSotck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Category", "Stock IN", "Stock Out", "Availabel Stock"
            }
        ));
        jTable_currentSotck.setRowHeight(25);
        jTable_currentSotck.setShowGrid(true);
        jTable_currentSotck.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_currentSotck);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_currentSotck;
    // End of variables declaration//GEN-END:variables
}
