/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModulComponent;
import Product_Component.AdjuetSotck_Compoent;
import Product_Component.ProductModul;
import Product_Component.StockDetail_Component;
import Product_Component.importStock_Component;
/**
 *
 * @author Da Phadenphorakden
 */
public class Navbar_product extends javax.swing.JPanel {

    /**
     * Creates new form Navbar_product
     */
    AdjuetSotck_Compoent asc = new  AdjuetSotck_Compoent();
    StockDetail_Component sdc;
    ProductModul prom = new ProductModul();
    importStock_Component msc = new importStock_Component();
    AdjuetSotck_Compoent as = new AdjuetSotck_Compoent();
    public Navbar_product() throws Exception {
        this.sdc = new StockDetail_Component();
        initComponents();
        Pro_MainContent.add("StockDetail",sdc);
        Pro_MainContent.add("ProductContnet",prom);
        Pro_MainContent.add("ImportStock",msc);
        Pro_MainContent.add("AdjustStock",as);
        
        
        sdc.setVisible(false);
        prom.setVisible(false);
        msc.setVisible(false);
        as.setVisible(false);
        asc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton_Product = new javax.swing.JButton();
        jButton_ImportStock = new javax.swing.JButton();
        jButton_AdjustStock = new javax.swing.JButton();
        jButton_StockDetail = new javax.swing.JButton();
        Pro_MainContent = new javax.swing.JLayeredPane();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1003, 60));

        jButton_Product.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_Product.setText("Product");
        jButton_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProductActionPerformed(evt);
            }
        });

        jButton_ImportStock.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_ImportStock.setText("Import Stock");
        jButton_ImportStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImportStockActionPerformed(evt);
            }
        });

        jButton_AdjustStock.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_AdjustStock.setText("Adjust Stock");
        jButton_AdjustStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdjustStockActionPerformed(evt);
            }
        });

        jButton_StockDetail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_StockDetail.setText("Stock Detail");
        jButton_StockDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StockDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_StockDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ImportStock, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_AdjustStock, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ImportStock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AdjustStock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_StockDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        Pro_MainContent.setRequestFocusEnabled(false);
        Pro_MainContent.setLayout(new java.awt.CardLayout());
        add(Pro_MainContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProductActionPerformed
        prom.setVisible(true);
        msc.setVisible(false );
        sdc.setVisible(false);
        as.setVisible(false);
    }//GEN-LAST:event_jButton_ProductActionPerformed

    private void jButton_ImportStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImportStockActionPerformed
        prom.setVisible(false);
        msc.setVisible(true);
        sdc.setVisible(false);
        as.setVisible(false);
    }//GEN-LAST:event_jButton_ImportStockActionPerformed

    private void jButton_AdjustStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdjustStockActionPerformed
        prom.setVisible(false);
        msc.setVisible(false );
        sdc.setVisible(false);
        as.setVisible(true );
    }//GEN-LAST:event_jButton_AdjustStockActionPerformed

    private void jButton_StockDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StockDetailActionPerformed
        prom.setVisible(false);
        msc.setVisible(false );
        sdc.setVisible(true);
        as.setVisible(false);
    }//GEN-LAST:event_jButton_StockDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Pro_MainContent;
    private javax.swing.JButton jButton_AdjustStock;
    private javax.swing.JButton jButton_ImportStock;
    private javax.swing.JButton jButton_Product;
    private javax.swing.JButton jButton_StockDetail;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
