/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModulComponent;

import UI.ExpensesFrm;
import UI.IncomeFrm;
import UI.IncomeRFrm;

/**
 *
 * @author Da Phadenphorakden
 */
public class Navbar_Home extends javax.swing.JPanel {

    /**
     * Creates new form Navbar_Home
     */
    HomeModul Dashboard = new HomeModul();
    IncomeFrm income = new IncomeFrm();
    ExpensesFrm expenses;
    IncomeRFrm incomeR = new IncomeRFrm();

    public Navbar_Home() throws Exception {
        this.expenses = new ExpensesFrm();
        initComponents();
        Main_jLayeredPane.add("Dashboard", Dashboard);
        Main_jLayeredPane.add("Revenu", income);
        Main_jLayeredPane.add("Expenses", expenses);
        Main_jLayeredPane.add("Income", incomeR);

        Dashboard.setVisible(false);
        income.setVisible(false);
        expenses.setVisible(false);
        incomeR.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_Income = new javax.swing.JButton();
        btn_expenses = new javax.swing.JButton();
        btnIncome = new javax.swing.JButton();
        btn_Dashboard = new javax.swing.JButton();
        Main_jLayeredPane = new javax.swing.JLayeredPane();

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1003, 60));

        btn_Income.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Income.setText("Revenu");
        btn_Income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IncomeActionPerformed(evt);
            }
        });

        btn_expenses.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_expenses.setText("Expenses");
        btn_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expensesActionPerformed(evt);
            }
        });

        btnIncome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnIncome.setText("Income");
        btnIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeActionPerformed(evt);
            }
        });

        btn_Dashboard.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_Dashboard.setText("DashBoard");
        btn_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Income, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Income, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Main_jLayeredPane.setBackground(new java.awt.Color(255, 255, 255));
        Main_jLayeredPane.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Main_jLayeredPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_jLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IncomeActionPerformed
        Dashboard.setVisible(false);
        income.setVisible(true);
        expenses.setVisible(false);
        incomeR.setVisible(false);
    }//GEN-LAST:event_btn_IncomeActionPerformed

    private void btn_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expensesActionPerformed
        Dashboard.setVisible(false);
        income.setVisible(false);
        expenses.setVisible(true);
        incomeR.setVisible(false);
    }//GEN-LAST:event_btn_expensesActionPerformed

    private void btnIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeActionPerformed
        Dashboard.setVisible(false);
        income.setVisible(false);
        expenses.setVisible(false);
        incomeR.setVisible(true);
    }//GEN-LAST:event_btnIncomeActionPerformed

    private void btn_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DashboardActionPerformed
        Dashboard.setVisible(true);
        income.setVisible(false);
        expenses.setVisible(false);
        incomeR.setVisible(false);
    }//GEN-LAST:event_btn_DashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Main_jLayeredPane;
    private javax.swing.JButton btnIncome;
    private javax.swing.JButton btn_Dashboard;
    private javax.swing.JButton btn_Income;
    private javax.swing.JButton btn_expenses;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
