package ModulComponent;

import ModulComponent.subComponent.Supplier.Sale.InvoicePanel;
import ModulComponent.subComponent.Supplier.Sale.MenuProduct;
import ModulComponent.subComponent.Supplier.Sale.SaleList;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;




public class SaleModul extends javax.swing.JPanel {
   
    MenuProduct men = new MenuProduct();
    SaleList sl = new SaleList();
    private InvoicePanel in;

    public SaleModul() throws SQLException {
        this.in = new InvoicePanel();
        initComponents();
        mainConentSale.add(men);
        mainConentSale.add(sl);
        
        men.setVisible(false);
        sl.setVisible(false);
       
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_sale_menu = new javax.swing.JButton();
        jButton_saleList = new javax.swing.JButton();
        jButton_refresh = new javax.swing.JButton();
        jButton_gennerateInvoice = new javax.swing.JButton();
        jButton_print_sale_list = new javax.swing.JButton();
        mainConentSale = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1072, 60));

        jButton_sale_menu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_sale_menu.setText("Menu");
        jButton_sale_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sale_menuActionPerformed(evt);
            }
        });

        jButton_saleList.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_saleList.setText("Sale List");
        jButton_saleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saleListActionPerformed(evt);
            }
        });

        jButton_refresh.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_refresh.setText("Refresh");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });

        jButton_gennerateInvoice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_gennerateInvoice.setText("Generate Invoice");
        jButton_gennerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gennerateInvoiceActionPerformed(evt);
            }
        });

        jButton_print_sale_list.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_print_sale_list.setText("Print");
        jButton_print_sale_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_print_sale_listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton_sale_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_saleList, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gennerateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addComponent(jButton_print_sale_list, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_saleList, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_sale_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_gennerateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_print_sale_list, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        mainConentSale.setLayout(new java.awt.CardLayout());
        add(mainConentSale, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sale_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sale_menuActionPerformed
     
        men.setVisible(true);
        sl.setVisible(false);
        men.setCard();
    }//GEN-LAST:event_jButton_sale_menuActionPerformed

    private void jButton_saleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saleListActionPerformed
        men.setVisible(false);
        sl.setVisible(true);
        sl.showInvoiceDBInTabel();
    }//GEN-LAST:event_jButton_saleListActionPerformed

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
       men.setCard();
       
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jButton_gennerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gennerateInvoiceActionPerformed
        
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            frame.add(new InvoicePanel(), BorderLayout.CENTER);
        } catch (SQLException ex) {
            Logger.getLogger(SaleModul.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.pack();
        frame.setLocationRelativeTo(null); 
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton_gennerateInvoiceActionPerformed

    private void jButton_print_sale_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_print_sale_listActionPerformed
        sl.printSaleList();
    }//GEN-LAST:event_jButton_print_sale_listActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_gennerateInvoice;
    private javax.swing.JButton jButton_print_sale_list;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButton_saleList;
    private javax.swing.JButton jButton_sale_menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane mainConentSale;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the in
     */
    public InvoicePanel getIn() {
        return in;
    }

    /**
     * @param in the in to set
     */
    public void setIn(InvoicePanel in) {
        this.in = in;
    }

   
    
}
