package ModulComponent;

import ModulComponent.subComponent.Supplier.Order;
import ModulComponent.subComponent.Supplier.VendorList;

public class SupplierModul extends javax.swing.JPanel {
    
    Order or = new Order();
    VendorList vn = new VendorList();
    public SupplierModul() {
        initComponents();
        mainContentSupplier.add("Order",or);
        mainContentSupplier.add("VendorList",vn);
        
        or.setVisible(false);
        vn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton_vendor = new javax.swing.JButton();
        jButton_order = new javax.swing.JButton();
        mainContentSupplier = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1003, 60));

        jButton_vendor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_vendor.setText("Vendors List");
        jButton_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vendorActionPerformed(evt);
            }
        });

        jButton_order.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_order.setText("Orders");
        jButton_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_orderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_order, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(735, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_order, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        mainContentSupplier.setLayout(new java.awt.CardLayout());
        add(mainContentSupplier, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vendorActionPerformed
        or.setVisible(false);
        vn.setVisible(true);
    }//GEN-LAST:event_jButton_vendorActionPerformed

    private void jButton_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_orderActionPerformed
        or.setVisible(true);
        vn.setVisible(false);
    }//GEN-LAST:event_jButton_orderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_order;
    private javax.swing.JButton jButton_vendor;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLayeredPane mainContentSupplier;
    // End of variables declaration//GEN-END:variables
}
