package ModulComponent;

import ModulComponent.subComponent.Supplier.Order;
import ModulComponent.subComponent.Supplier.VendorList;
import UI.PermissionFrm;
import UI.RoleFrm;
import UI.UserInternalFrm;

public class UserRole extends javax.swing.JPanel {

    PermissionFrm perfrm;
    RoleFrm rolefrm = new RoleFrm();
    UserInternalFrm userfrm;

    public UserRole() throws Exception {
        this.perfrm = new PermissionFrm();
        this.userfrm = new UserInternalFrm();
        initComponents();
        mainContentSupplier.add("User", userfrm);
        mainContentSupplier.add("Role", rolefrm);
        mainContentSupplier.add("Permission", perfrm);

        userfrm.setVisible(false);
        rolefrm.setVisible(false);
        perfrm.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton_vendor = new javax.swing.JButton();
        jButton_order = new javax.swing.JButton();
        btn_permission = new javax.swing.JButton();
        mainContentSupplier = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1003, 60));

        jButton_vendor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_vendor.setText("User");
        jButton_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vendorActionPerformed(evt);
            }
        });

        jButton_order.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_order.setText("Role");
        jButton_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_orderActionPerformed(evt);
            }
        });

        btn_permission.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_permission.setText("Permission");
        btn_permission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_permissionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_order, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_permission, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_order, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_permission, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        mainContentSupplier.setLayout(new java.awt.CardLayout());
        add(mainContentSupplier, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vendorActionPerformed
        rolefrm.setVisible(false);
        userfrm.setVisible(true);
        perfrm.setVisible(false);
    }//GEN-LAST:event_jButton_vendorActionPerformed

    private void jButton_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_orderActionPerformed
        rolefrm.setVisible(true);
        userfrm.setVisible(false);
        perfrm.setVisible(false);
    }//GEN-LAST:event_jButton_orderActionPerformed

    private void btn_permissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_permissionActionPerformed
        userfrm.setVisible(false);
        rolefrm.setVisible(false);
        perfrm.setVisible(true);
    }//GEN-LAST:event_btn_permissionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_permission;
    private javax.swing.JButton jButton_order;
    private javax.swing.JButton jButton_vendor;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLayeredPane mainContentSupplier;
    // End of variables declaration//GEN-END:variables
}
