/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package ModulComponent.subComponent.Supplier.Sale;
    
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.io.File;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Da Phadenphorakden
 */
public class DialogInvoiceList extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form DailogInvoiceList
     */
    public DialogInvoiceList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
//        String cancelName = "cancel";
//        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
//        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
//        ActionMap actionMap = getRootPane().getActionMap();
//        actionMap.put(cancelName, new AbstractAction() {
//            public void actionPerformed(ActionEvent e) {
//                doClose(RET_CANCEL);
//            }
//        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnperview = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        spinnerStartDate = new javax.swing.JSpinner();
        spinnerEndDate = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboReportFormat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btnperview.setText("Preview");
        btnperview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperviewActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        spinnerStartDate.setFont(new java.awt.Font("Geist Mono", 0, 18)); // NOI18N
        spinnerStartDate.setModel(new javax.swing.SpinnerDateModel());
        spinnerStartDate.setDoubleBuffered(true);
        spinnerStartDate.setEditor(new javax.swing.JSpinner.DateEditor(spinnerStartDate, "yyyy-MM-dd"));

        spinnerEndDate.setFont(new java.awt.Font("Geist Mono", 0, 18)); // NOI18N
        spinnerEndDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1753528640207L), null, null, java.util.Calendar.DAY_OF_MONTH));
        spinnerEndDate.setDoubleBuffered(true);
        spinnerEndDate.setEditor(new javax.swing.JSpinner.DateEditor(spinnerEndDate, "yyyy-MM-dd"));

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 16)); // NOI18N
        jLabel1.setText("End Date (YYYY-MM-DD)");

        jLabel2.setFont(new java.awt.Font("Geist Mono", 0, 16)); // NOI18N
        jLabel2.setText("Start Date (YYYY-MM-DD)");

        cboReportFormat.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        cboReportFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily Report", "Monthly Report", "All Report" }));

        jLabel3.setFont(new java.awt.Font("Geist Mono", 0, 16)); // NOI18N
        jLabel3.setText("Report Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnperview, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spinnerEndDate)
                                .addComponent(spinnerStartDate)
                                .addComponent(cboReportFormat, 0, 239, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboReportFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(btnperview))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnperview);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnperviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperviewActionPerformed

        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String startDate = df.format(this.spinnerStartDate.getValue());
            String endDate = df.format(this.spinnerEndDate.getValue());
            System.out.println(startDate);
            Class.forName("org.postgresql.Driver");
            String constr = "jdbc:postgresql://localhost:5432/Inventory?user=postgres&password=dan@12345&connectTimeout=30";
            Connection con = DriverManager.getConnection(constr);
            String reportPath = "";//./resources/...
            String sql = "";
            switch (this.cboReportFormat.getSelectedIndex()) {
                case 0:
                        //reportPath = ClassLoader.getSystemResource("./src/Reports/DailyInvoiceReport.jrxml").getPath();
                        reportPath = "./src/Reports/DailyInvoiceReport.jrxml";//./src/dbdata/
                        sql = "SELECT invoice_id, invoice_date, total_amount FROM public.invoices where invoice_date = '"+startDate+"'";
                        doClose(RET_OK);
                    break;
                case 1:
                        reportPath = "./src/Reports/MonthlyInvoiceReport.jrxml";//./src/dbdata/
                        sql = "SELECT invoice_id, invoice_date, total_amount FROM public.invoices ";
                        doClose(RET_OK);
                    break;
                case 2:
                        reportPath = "./src/Reports/AllInvoiceReport.jrxml";//./src/dbdata/
                        sql = "SELECT invoice_id, invoice_date, total_amount FROM public.invoices ";
                        doClose(RET_OK);
                    break;
                default:
                    throw new AssertionError();
            }
            JRDesignQuery qry = new JRDesignQuery();
            JasperDesign jd = JRXmlLoader.load(reportPath);
            qry.setText(sql);
            jd.setQuery(qry);

            //if you want no change result
            //JasperReport jr = JasperCompileManager.compileReport(reportPath);
            
            //update data source to change the result.
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap<String, Object> params = new HashMap<>();
            JasperPrint jp = JasperFillManager.fillReport(jr, params, con);

            JasperViewer.viewReport(jp, false);
            con.close();
        } catch (SQLException | JRException | ClassNotFoundException ex) {

        }
    }//GEN-LAST:event_btnperviewActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogInvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogInvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogInvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogInvoiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogInvoiceList dialog = new DialogInvoiceList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnperview;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cboReportFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spinnerEndDate;
    private javax.swing.JSpinner spinnerStartDate;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
