/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModulComponent.subComponent.Supplier.Sale;

import DAO.invoiceAmounttodayDao;
import DAO.sum_invoiceDao;
import DAO.sum_totalAmountDao;
import DTO.sum_invoice;
import DTO.Invoice_list;
import DTO.sum_invoiceAmounttoday;
import DTO.sum_totalAmount;
import Database.DatabaseConfig;
import Product_Component.ProductModul;
import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Da Phadenphorakden
 */
public class Invoices_list extends javax.swing.JPanel {

    /**
     * Creates new form Invoices_list
     */
    sum_invoiceDao sum_inv = new sum_invoiceDao();
    invoiceAmounttodayDao sum_amount = new invoiceAmounttodayDao();
    sum_totalAmountDao sum_totalAdmount = new sum_totalAmountDao();

    public Invoices_list() throws Exception {
        initComponents();
        showInTabel();
        diplaybox();

        // Create the desired font for the header
        JTableHeader header = tbl_invoice_list.getTableHeader();
        Font headerFont = new Font("Century Gothic", Font.BOLD, 18); // Example: Bold, Size 14
        header.setFont(headerFont);
    }

    public void diplaybox() {
        // Diplay Total Invoice
        List<sum_invoice> show = sum_inv.sum_invoiceDto();
        total_invoice_today.setText(String.valueOf(show.get(0).getSumInvoice()));

        // Diplay Total Today Amount
        List<sum_invoiceAmounttoday> sum_amount_today = sum_amount.sum_invoiceTAmounttodaysDto();
        today_amount_total.setText(String.valueOf(sum_amount_today.get(0).getInvoiceAmounttoday() + "$"));

        // Diplay Total Amount
        List<sum_totalAmount> sum_totalAmount = sum_totalAdmount.sum_totalAmountDto();
        total_amount.setText(String.valueOf(sum_totalAmount.get(0).getInvoiceAmountTotal()) + "$");
    }

    //getData from database
    public List<Invoice_list> getDataInvoice_listDto() {
        List<Invoice_list> list = new ArrayList<>();
        try {
            String sql = "SELECT invoice_id, invoice_date, total_amount FROM public.invoices ORDER BY invoice_id DESC ";
            PreparedStatement pstmt = DatabaseConfig.getConnection().prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            Invoice_list getdata;
            while (rs.next()) {
                getdata = new Invoice_list(
                        rs.getInt("invoice_id"),
                        rs.getDate("invoice_date"),
                        rs.getDouble("total_amount"));
                list.add(getdata);
            }
        } catch (SQLException e) {
            Logger.getLogger(ProductModul.class.getName()).log(Level.SEVERE, null, e);
        }
        return list;
    }
    //show data to table

    public void showInTabel() {
        List<Invoice_list> invoice_List = getDataInvoice_listDto();
        DefaultTableModel model = (DefaultTableModel) tbl_invoice_list.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];

        for (int i = 0; i < invoice_List.size(); i++) {
            row[0] = "INV" + invoice_List.get(i).getInvoice_id();
            row[1] = invoice_List.get(i).getInvoice_date();
            row[2] = "$" + invoice_List.get(i).getTotal_amount();
            model.addRow(row);

        }
    }
    //get sum today invoice today

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        report_invoiceList = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        report_daily = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_invoice_list = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        total_invoice_today = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        today_amount_total = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        total_amount = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jSeparator1.setEnabled(false);
        jToolBar1.add(jSeparator1);

        jButton1.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(80, 26));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jSeparator2.setEnabled(false);
        jToolBar1.add(jSeparator2);

        report_invoiceList.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        report_invoiceList.setText("Report DTD");
        report_invoiceList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report_invoiceList.setFocusable(false);
        report_invoiceList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        report_invoiceList.setPreferredSize(new java.awt.Dimension(95, 26));
        report_invoiceList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        report_invoiceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_invoiceListActionPerformed(evt);
            }
        });
        jToolBar1.add(report_invoiceList);

        jSeparator3.setEnabled(false);
        jToolBar1.add(jSeparator3);

        report_daily.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        report_daily.setText("General Report");
        report_daily.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        report_daily.setFocusable(false);
        report_daily.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        report_daily.setPreferredSize(new java.awt.Dimension(118, 26));
        report_daily.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        report_daily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_dailyActionPerformed(evt);
            }
        });
        jToolBar1.add(report_daily);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_invoice_list.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        tbl_invoice_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Invoice Date", "Total Amount"
            }
        ));
        tbl_invoice_list.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_invoice_list);
        if (tbl_invoice_list.getColumnModel().getColumnCount() > 0) {
            tbl_invoice_list.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel1.setText("Total Invoice Today");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        total_invoice_today.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        total_invoice_today.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel3.add(total_invoice_today, gridBagConstraints);

        jPanel6.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel2.setText("Total Amount Today");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel2, gridBagConstraints);

        today_amount_total.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        today_amount_total.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel4.add(today_amount_total, gridBagConstraints);

        jPanel6.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel3.setText("Total Amount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jLabel3, gridBagConstraints);

        total_amount.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        total_amount.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel5.add(total_amount, gridBagConstraints);

        jPanel6.add(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        diplaybox();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void report_invoiceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_invoiceListActionPerformed
        // TODO add your handling code here:
        DialogInvoiceList2 dialog_invoiceList = new DialogInvoiceList2(null, true);
        dialog_invoiceList.setTitle("Report Invoice List");
        dialog_invoiceList.setVisible(true);

    }//GEN-LAST:event_report_invoiceListActionPerformed

    private void report_dailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_dailyActionPerformed
        DialogInvoiceList dialog_invoiceList = new DialogInvoiceList(null, true);
        dialog_invoiceList.setTitle("Report Invoice List");
        dialog_invoiceList.setVisible(true);
        
//        Connection conn = null;
//        try {
//            // 1. Connect to PostgreSQL database
//            conn = DriverManager.getConnection(
//                "jdbc:postgresql://localhost:5432/Inventory?user=postgres&password=dan@12345&connectTimeout=30"
//            );
//            System.out.println("✅ Database connection established.");
//
//            // 2. Load JRXML report file from classpath
//            InputStream jrxmlStream = Invoices_list.class.getClassLoader().getResourceAsStream("Reports/newDaily.jrxml");
//
//            if (jrxmlStream == null) {
//                throw new JRException("newDaily.jrxml not found. Ensure it's in src/Reports and properly added to the classpath.");
//            }
//
//            // 3. Compile the JRXML to JasperReport
//            JasperReport jasperReport = JasperCompileManager.compileReport(jrxmlStream);
//            System.out.println("JRXML compiled successfully.");
//
//            // 4. Set report parameters
//            Map<String, Object> parameters = new HashMap<>();
//            parameters.put("REPORT_TITLE", "Daily Invoice Report");
//            parameters.put("REPORT_DATE_FILTER", java.sql.Date.valueOf(LocalDate.of(2025, 8, 4))); // Example date
//
//            // 5. Fill the report with data from the DB
//            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
//            System.out.println("Report filled with data.");
//
//            // 6. Show the report in viewer (GUI)
//            JasperViewer.viewReport(jasperPrint, false);
//            System.out.println("Report displayed successfully.");
//           
//        } catch (JRException e) {
//            System.err.println("JasperReport Error: " + e.getMessage());
//        } catch (SQLException e) {
//            System.err.println("Database Error: " + e.getMessage());
//        } finally {
//            // 7. Always close DB connection
//            if (conn != null) {
//                try {
//                    conn.close();
//                    System.out.println("🔒 Database connection closed.");
//                } catch (SQLException e) {
//                    System.err.println("⚠️ Failed to close DB connection: " + e.getMessage());
//                }
//            }
//        }


    }//GEN-LAST:event_report_dailyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton report_daily;
    private javax.swing.JButton report_invoiceList;
    private javax.swing.JTable tbl_invoice_list;
    private javax.swing.JLabel today_amount_total;
    private javax.swing.JLabel total_amount;
    private javax.swing.JLabel total_invoice_today;
    // End of variables declaration//GEN-END:variables
}
