
package ModulComponent.subComponent.Supplier.Sale;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import Logic.product;
import ModulComponent.ProductModul;
import ModulComponent.subComponent.Supplier.Sale.productCard;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


public final class MenuProduct extends javax.swing.JPanel {
    
    private static final String url = "jdbc:postgresql://localhost:5432/Inventory"; // Replace with your DB details
    private static final String user = "postgres"; // Replace with your DB username
    private static final String password = "dan@12345"; // Replace with your DB password
    private static final long serialVersionUID = 1L;
   
    public String name;
    public String category;
    public Double price;
    public Integer quantity;
    public String image;
    private JPanel displayPanel;
    public MenuProduct(String name, String category, Double price, Integer quantity, String image) {
        this.name = name;
        this.category = category;
        this.price = price;
        this.quantity = quantity;
        this.image = image;
    }
    
    public MenuProduct() {
       
        initComponents();
         
       
       
    
    }
    

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }
    
    
  
    public void setCard()
    {   
      
       jPanel2.removeAll();
       jPanel2.setLayout(new GridLayout(0, 4, 10, 10));
        List<productCard> cards = getProductsList();
        for (productCard card : cards) {
            JPanel cardPanel = card.createCardPanel();
            // Ensure the card panel has a border to simulate grid lines
            cardPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
            // Set the preferred size for the card panel
            cardPanel.setPreferredSize(new Dimension(250,350));
            jPanel2.add(cardPanel);
        }

        jPanel2.revalidate();
        jPanel2.repaint();

    }
   
     // function that return an array list
    public List<productCard> getProductsList()
    {   
        List<productCard> cards = new ArrayList<>();
        try(Connection connection = DriverManager.getConnection(url, user, password)) {
            String query = "SELECT * FROM products ORDER BY id DESC;";
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {                
               String name = rs.getString("name");
               String category = rs.getString("category");
               Double price =  rs.getDouble("price");
               Integer quantity = rs.getInt("quantity");
               String image = rs.getString("image");
               cards.add(new productCard( name,category, price,quantity,image));       
            }
            
             
        } catch (Exception e) {
            Logger.getLogger(ProductModul.class.getName()).log(Level.SEVERE, null, e);
        }
        return cards;
       
    }
   
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1072, 567));
        setMinimumSize(new java.awt.Dimension(1072, 567));
        setPreferredSize(new java.awt.Dimension(1072, 567));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setRequestFocusEnabled(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
