/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DTO.ExspenseDto;
import DAO.ExspenseDao;
import DTO.UserDto;
import Database.DatabaseConfig;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Da Phadenphorakden
 */

public class ExpensesFrm extends javax.swing.JPanel {

    /**
     * Creates new form ExpensesFrm
     */
    ExspenseDao dao = new ExspenseDao();
    public ExpensesFrm() throws Exception {
        initComponents();
        diplaybox();
        List<ExspenseDto> result = dao.loadExspense();
        this.showIncomeTable(result);
        
        
         // Create the desired font for the header
        JTableHeader header = tbl_Expenses.getTableHeader();
        Font headerFont = new Font("Century Gothic", Font.BOLD, 18); // Example: Bold, Size 14
        header.setFont(headerFont);
    }
    public void showIncomeTable( List<ExspenseDto> Exspense) {
        //insert into jtable
        DefaultTableModel tbl = (DefaultTableModel) this.tbl_Expenses.getModel();
        tbl.setRowCount(0);//clear
        for (ExspenseDto dto : Exspense) {
            tbl.addRow(new Object[]{dto.getExspense_id(),dto.getExspense_date(), dto.getExspense_purpose(), dto.getExspense_description(), dto.getQuantity(),dto.getExspense_price()+"$",dto.getTotal()+"$"});
        }
        if (tbl.getRowCount() > 0) {
            this.tbl_Expenses.setRowSelectionInterval(0, 0);
        }
    }
    public void diplaybox() {
        //Box 1
        // Diplay Total Today Amount
        List<ExspenseDto> sum_amount_today = dao.dailyExspense();
        label_dailyExspenses.setText(String.valueOf(sum_amount_today.get(0).getDailyExspenses()+ "$"));

        //Box 2
        // Diplay Total incomeCurrentMonthly
        List<ExspenseDto> sumMonthlyExspense = dao.monthlyExspense();
        label_monthlyExspenses.setText(String.valueOf(sumMonthlyExspense.get(0).getMonthlyExspenses()+ "$"));

        //Box 3
        // Diplay Total Amount
        List<ExspenseDto> sumTotalExspense = dao.totalExspense();
        label_totalExspenses.setText(String.valueOf(sumTotalExspense.get(0).getTotalExspenses()) + "$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_CeateExspense = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEdit = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnDelete = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_report = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Expenses = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        asads = new javax.swing.JLabel();
        label_dailyExspenses = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_monthlyExspenses = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_totalExspenses = new javax.swing.JLabel();

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btn_CeateExspense.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_CeateExspense.setText("Create");
        btn_CeateExspense.setFocusable(false);
        btn_CeateExspense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_CeateExspense.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_CeateExspense.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_CeateExspense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CeateExspenseActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_CeateExspense);
        jToolBar1.add(jSeparator2);

        btnEdit.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setPreferredSize(new java.awt.Dimension(90, 35));
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);
        jToolBar1.add(jSeparator4);

        btnDelete.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 35));
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);
        jToolBar1.add(jSeparator5);

        btn_report.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_report.setText("Report");
        btn_report.setFocusable(false);
        btn_report.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_report.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_report.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_report);
        jToolBar1.add(jSeparator3);

        btn_refresh.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_refresh.setText("Refesh");
        btn_refresh.setFocusable(false);
        btn_refresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_refresh.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_refresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_refresh);

        tbl_Expenses.setFont(new java.awt.Font("Geist Mono", 0, 18)); // NOI18N
        tbl_Expenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exspenses ID", "Date", "Porpose", "Decription", "Quantity", "Price", "Total"
            }
        ));
        tbl_Expenses.setRowHeight(20);
        jScrollPane1.setViewportView(tbl_Expenses);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        asads.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        asads.setText("Daily Exspenses");
        jPanel5.add(asads, new java.awt.GridBagConstraints());

        label_dailyExspenses.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        label_dailyExspenses.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel5.add(label_dailyExspenses, gridBagConstraints);

        jPanel1.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel1.setText("Monthly Exspenses");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        label_monthlyExspenses.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        label_monthlyExspenses.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel3.add(label_monthlyExspenses, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel2.setText("Total Exspenses");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel2, gridBagConstraints);

        label_totalExspenses.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        label_totalExspenses.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel4.add(label_totalExspenses, gridBagConstraints);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // Refresh
        List<ExspenseDto> result = null;
        try {
            result = dao.loadExspense();
            diplaybox();
        } catch (Exception ex) {
            Logger.getLogger(ExpensesFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.showIncomeTable(result);
      
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_CeateExspenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CeateExspenseActionPerformed
        //Create Form Dailog
        DialogCreateExspense createFormCreateExspense = new DialogCreateExspense(null,true);
        createFormCreateExspense.setVisible(true);
    }//GEN-LAST:event_btn_CeateExspenseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        DefaultTableModel tbl = (DefaultTableModel) this.tbl_Expenses.getModel();
        int index = tbl_Expenses.getSelectedRow();
        int exspenses_id = (Integer) tbl.getValueAt(index, 0);
        
        DialogEditExspense EditExspense = null;
        try {
            EditExspense = new DialogEditExspense(null,exspenses_id);
        } catch (SQLException ex) {
            Logger.getLogger(ExpensesFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        EditExspense.setVisible(true);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         try {
            if (this.tbl_Expenses.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No record selected!");
                return;
            }
            int opt = JOptionPane.showConfirmDialog(this, "Are you sure to delete this record?", "Delete", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {
                DefaultTableModel tbl = (DefaultTableModel) this.tbl_Expenses.getModel();
                int idx = this.tbl_Expenses.getSelectedRow();
                long uid = Long.parseLong(tbl.getValueAt(idx, 0).toString());
                if (dao.delete(uid) == true) {
                    tbl.removeRow(idx);
                    diplaybox();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asads;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btn_CeateExspense;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label_dailyExspenses;
    private javax.swing.JLabel label_monthlyExspenses;
    private javax.swing.JLabel label_totalExspenses;
    private javax.swing.JTable tbl_Expenses;
    // End of variables declaration//GEN-END:variables
}
