/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.invoiceAmounttodayDao;
import DAO.sum_totalAmountDao;
import DTO.Invoice_list;
import DTO.sum_invoice;
import DTO.sum_invoiceAmounttoday;
import DTO.sum_totalAmount;
import Database.DatabaseConfig;
import Product_Component.ProductModul;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Da Phadenphorakden
 */
public class IncomeFrm extends javax.swing.JPanel {

    /**
     * Creates new form InvcomeFrm
     */
    sum_totalAmountDao sum_total_income = new sum_totalAmountDao();
    invoiceAmounttodayDao sum_amount = new invoiceAmounttodayDao();

    public IncomeFrm() {
        initComponents();
        diplaybox();
        showInTabel();
        
        
        // Create the desired font for the header
        JTableHeader header = tbl_invoice_list.getTableHeader();
        Font headerFont = new Font("Century Gothic", Font.BOLD, 18); // Example: Bold, Size 14
        header.setFont(headerFont);
    }

    public void diplaybox() {
        //Box 1
        // Diplay Total Today Amount
        List<sum_invoiceAmounttoday> sum_amount_today = sum_amount.sum_invoiceTAmounttodaysDto();
        total_Income_today.setText(String.valueOf(sum_amount_today.get(0).getInvoiceAmounttoday() + "$"));

        //Box 2
        // Diplay Total incomeCurrentMonthly
        List<sum_invoiceAmounttoday> incomeCurrentMonthly = sum_amount.incomeCurrentMonthDto();
        Monthly_amount_total.setText(String.valueOf(incomeCurrentMonthly.get(0).getIncomeCurrentMonthly() + "$"));

        //Box 3
        // Diplay Total Amount
        List<sum_totalAmount> sum_totalAmount = sum_total_income.sum_totalAmountDto();
        total_Income.setText(String.valueOf(sum_totalAmount.get(0).getInvoiceAmountTotal()) + "$");
    }

    public List<Invoice_list> getDataInvoice_listDto() {
        List<Invoice_list> list = new ArrayList<>();
        try {
            String sql = "SELECT invoice_id, invoice_date, total_amount FROM public.invoices ORDER BY invoice_id DESC ";
            PreparedStatement pstmt = DatabaseConfig.getConnection().prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            Invoice_list getdata;
            while (rs.next()) {
                getdata = new Invoice_list(
                        rs.getInt("invoice_id"),
                        rs.getDate("invoice_date"),
                        rs.getDouble("total_amount"));
                list.add(getdata);
            }
        } catch (SQLException e) {
            Logger.getLogger(ProductModul.class.getName()).log(Level.SEVERE, null, e);
        }
        return list;
    }
    //show data to table

    public void showInTabel() {
        List<Invoice_list> invoice_List = getDataInvoice_listDto();
        DefaultTableModel model = (DefaultTableModel) tbl_invoice_list.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];

        for (int i = 0; i < invoice_List.size(); i++) {
            row[0] = "INV" + invoice_List.get(i).getInvoice_id();
            row[1] = invoice_List.get(i).getInvoice_date();
            row[2] = "$" + invoice_List.get(i).getTotal_amount();
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_refresh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_report = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        total_Income_today = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Monthly_amount_total = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        total_Income = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_invoice_list = new javax.swing.JTable();

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btn_refresh.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_refresh.setText("Refesh");
        btn_refresh.setFocusable(false);
        btn_refresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_refresh.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_refresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_refresh);
        jToolBar1.add(jSeparator2);

        btn_report.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_report.setText("Report");
        btn_report.setFocusable(false);
        btn_report.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_report.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_report.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_report);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel1.setText("Total Daily Revenu");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        total_Income_today.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        total_Income_today.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel3.add(total_Income_today, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel2.setText("Total Monthly Revenu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel2, gridBagConstraints);

        Monthly_amount_total.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        Monthly_amount_total.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel4.add(Monthly_amount_total, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel3.setText("Total Revenu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jLabel3, gridBagConstraints);

        total_Income.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        total_Income.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel5.add(total_Income, gridBagConstraints);

        jPanel1.add(jPanel5);

        tbl_invoice_list.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        tbl_invoice_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Invoice Date", "Total Amount"
            }
        ));
        tbl_invoice_list.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_invoice_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // Refresh
        diplaybox();
        showInTabel();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        revenuReport rvR = new revenuReport(null, true);
        rvR.setTitle("Revenue Report");
        rvR.setVisible(true);
    }//GEN-LAST:event_btn_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Monthly_amount_total;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_invoice_list;
    private javax.swing.JLabel total_Income;
    private javax.swing.JLabel total_Income_today;
    // End of variables declaration//GEN-END:variables
}
