/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.ExspenseDao;
import DAO.IncomeDao;
import DAO.invoiceAmounttodayDao;
import DAO.sum_totalAmountDao;
import DTO.ExspenseDto;
import DTO.IncomeDto;
import DTO.Invoice_list;
import DTO.sum_invoice;
import DTO.sum_invoiceAmounttoday;
import DTO.sum_totalAmount;
import Database.DatabaseConfig;
import Product_Component.ProductModul;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Da Phadenphorakden
 */
public class IncomeRFrm extends javax.swing.JPanel {

    /**
     * Creates new form InvcomeFrm
     */
    IncomeDao dao = new IncomeDao();
    ExspenseDao exspensesDao = new ExspenseDao();
    public IncomeRFrm() throws Exception {
        initComponents();
        diplaybox();
        getIncomeTable();

        
        
        // Create the desired font for the header
        JTableHeader header = tbl_invoice_list.getTableHeader();
        Font headerFont = new Font("Century Gothic", Font.BOLD, 18); // Example: Bold, Size 14
        header.setFont(headerFont);
    }

    public void diplaybox() throws Exception {
        //Box 1
        // Diplay Total Today Amount
        List<IncomeDto> getTotalIncomeOfProduct = dao.getIncomeOfProdeuct();
        label_incomeOfProduct.setText(String.valueOf(getTotalIncomeOfProduct.get(0).getIncome_of_produect()+ "$"));

        //Box 2
        // Diplay Total incomeCurrentMonthly
        List<ExspenseDto> totalExspenses = exspensesDao.totalExspense() ;
        label_totalExspenses.setText(String.valueOf(totalExspenses.get(0).getTotalExspenses()+ "$"));

        //Box 3
        // Diplay Total Amount
        List<IncomeDto> totalProductCode = dao.getTotalProdeuctCost();
        label_totalProductCost.setText(String.valueOf(totalProductCode.get(0).getTotal_productCost()) + "$");
    }

    public void getIncomeTable() throws Exception {
        List<IncomeDto> getDataIncomeTable = dao.loadIncomeToTable();
        DefaultTableModel tbl = (DefaultTableModel) this.tbl_invoice_list.getModel();
        tbl.setRowCount(0);//clear
        for (IncomeDto incomeDto : getDataIncomeTable) {
            tbl.addRow(new Object[]{
                incomeDto.getProduct_id(),
                incomeDto.getProduct_name(),
                incomeDto.getProduct_cate(),
                incomeDto.getProduct_stockin(),
                incomeDto.getTotal_cost()+"$",
                incomeDto.getTotal_cost()+"$",
                incomeDto.getProduct_stockout(),
                incomeDto.getProduct_price()+"$",
                incomeDto.getProduct_available(),
                incomeDto.getTotal_revenue()+"$",
                incomeDto.getIncome()+"$"
            });
            if (tbl.getRowCount() > 0) {
            this.tbl_invoice_list.setRowSelectionInterval(0, 0);
        }
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_refresh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_report = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_incomeOfProduct = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_totalExspenses = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        label_totalProductCost = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_invoice_list = new javax.swing.JTable();

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btn_refresh.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_refresh.setText("Refesh");
        btn_refresh.setFocusable(false);
        btn_refresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_refresh.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_refresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_refresh);
        jToolBar1.add(jSeparator2);

        btn_report.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_report.setText("Report");
        btn_report.setFocusable(false);
        btn_report.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_report.setPreferredSize(new java.awt.Dimension(90, 35));
        btn_report.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_report);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel1.setText("Total Income of Product ");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        label_incomeOfProduct.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        label_incomeOfProduct.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel3.add(label_incomeOfProduct, gridBagConstraints);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel2.setText("Total Exspenses");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel2, gridBagConstraints);

        label_totalExspenses.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        label_totalExspenses.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel4.add(label_totalExspenses, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jLabel3.setText("Total Product Cost");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel5.add(jLabel3, gridBagConstraints);

        label_totalProductCost.setFont(new java.awt.Font("Geist Mono", 0, 24)); // NOI18N
        label_totalProductCost.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel5.add(label_totalProductCost, gridBagConstraints);

        jPanel1.add(jPanel5);

        tbl_invoice_list.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        tbl_invoice_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Cate", "Product_IN", "Product Cost", "Total Cost", "Product Out", "Sale Price", "Available", "Total Revenu", "Total Income"
            }
        ));
        tbl_invoice_list.setRowHeight(25);
        jScrollPane2.setViewportView(tbl_invoice_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        try {
            // Refresh
            diplaybox();
//        showInTabel();
        } catch (Exception ex) {
            Logger.getLogger(IncomeRFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        incomeReport rvR = new incomeReport(null, true);
        rvR.setTitle("Exspenses Report");
        rvR.setVisible(true);
    }//GEN-LAST:event_btn_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel label_incomeOfProduct;
    private javax.swing.JLabel label_totalExspenses;
    private javax.swing.JLabel label_totalProductCost;
    private javax.swing.JTable tbl_invoice_list;
    // End of variables declaration//GEN-END:variables
}
