/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.PermissionDao;
import DTO.PermissionDto;
import Database.DatabaseConfig;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.TreeNode;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Da Phadenphorakden
 */
public class PermissionFrm extends javax.swing.JPanel {

    /**
     * Creates new form PermissionFrm
     */
    public PermissionFrm() throws Exception {
        initComponents();
        loadTreeItems();
        
        
         // Create the desired font for the header
        JTableHeader header = jTable3.getTableHeader();
        Font headerFont = new Font("Century Gothic", Font.BOLD, 18); // Example: Bold, Size 14
        header.setFont(headerFont);

    }

    public void loadTreeItems() {
        DefaultTreeModel model = (DefaultTreeModel) this.jTreeRole.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.setUserObject("System");
        DefaultMutableTreeNode documents = new DefaultMutableTreeNode("Role");
        try {
            String sql = "SELECT name\n"
                    + "	FROM public.role;";
            PreparedStatement pstmt = DatabaseConfig.getConnection().prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                String name = rs.getString("name");
                documents.add(new DefaultMutableTreeNode(name));
            }
            root.add(documents);
            rs.close();

        } catch (Exception e) {
            Logger.getLogger(DialogSetRole.class.getName()).log(Level.SEVERE, null, e);
        }
        model.reload();

    }

    public void showMenuItem(String role_name) {
        try {
             // Query to get menu items/permissions for the selected role
            String sql = "SELECT\n"
                    + "	r.id AS role_id,\n"
                    + "    r.name AS role_name,\n"
                    + "    p.name AS permission_name,\n"
                    + "    p.description AS permission_description\n"
                    + "FROM\n"
                    + "    role_permission rp\n"
                    + "JOIN\n"
                    + "    role r ON rp.role_id = r.id\n"
                    + "JOIN\n"
                    + "    permission p ON rp.permission_id = p.id\n"
                    + "WHERE\n"
                    + "	r.name = ?\n"
                    + "ORDER BY\n"
                    + "    r.name, p.name;";
            try (PreparedStatement pstmt = DatabaseConfig.getConnection().prepareStatement(sql)) {
                pstmt.setString(1, role_name);
                // Create table model to store query results
                try (ResultSet rs = pstmt.executeQuery()) {
                    // Create table model to store query results
                    DefaultTableModel tableModel = (DefaultTableModel) this.jTable3.getModel();
                    // Clear existing rows
                    tableModel.setRowCount(0);
                    // Populate table model with query results
                    while (rs.next()) {
                        Object[] row = {
                            rs.getInt("role_id"),
                            rs.getString("role_name"),
                            rs.getString("permission_name")
                        };
                        tableModel.addRow(row);
                    }   // Assuming jTableMenu is your JTable component
                    jTable3.setModel(tableModel);
                    // Clean up resources
//            conn.close();
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(PermissionFrm.class.getName()).log(Level.SEVERE, "Error fetching menu items", ex);
            JOptionPane.showMessageDialog(this, "Error loading menu items: " + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_create = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_edit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_delete = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_delete1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTreeRole = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btn_create.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_create.setText("Create");
        btn_create.setFocusable(false);
        btn_create.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_create.setMaximumSize(new java.awt.Dimension(80, 32));
        btn_create.setPreferredSize(new java.awt.Dimension(80, 32));
        btn_create.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_create);
        jToolBar1.add(jSeparator2);

        btn_edit.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setFocusable(false);
        btn_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_edit.setPreferredSize(new java.awt.Dimension(80, 32));
        btn_edit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_edit);
        jToolBar1.add(jSeparator3);

        btn_delete.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setFocusable(false);
        btn_delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_delete.setPreferredSize(new java.awt.Dimension(80, 32));
        btn_delete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_delete);
        jToolBar1.add(jSeparator4);

        btn_delete1.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_delete1.setText("Refresh");
        btn_delete1.setFocusable(false);
        btn_delete1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_delete1.setPreferredSize(new java.awt.Dimension(80, 32));
        btn_delete1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_delete1);

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 250));

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 48)); // NOI18N
        jLabel1.setText("PERMSSION ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Role");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("2");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Role");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("a");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("b");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("role");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeRole.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeRole.setMaximumSize(new java.awt.Dimension(150, 57));
        jTreeRole.setPreferredSize(new java.awt.Dimension(150, 57));
        jTreeRole.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeRoleValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jTreeRole);

        jSplitPane1.setLeftComponent(jScrollPane3);

        jTable3.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Role ID", "Role Name", "Permission Name"
            }
        ));
        jTable3.setRowHeight(20);
        jScrollPane4.setViewportView(jTable3);

        jSplitPane1.setRightComponent(jScrollPane4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeRoleValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeRoleValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) this.jTreeRole.getLastSelectedPathComponent();
        if (node.getLevel() != 0) {
            String role_name = node.getUserObject().toString();
            showMenuItem(role_name);
      
            
               //select index
//            DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) node.getParent();
//                try {
//                    int role_id = node.getIndex(node);
//                    showMenuItem(role_id);
//                } catch (Exception ex) {
//                    Logger.getLogger(PermissionFrm.class.getName()).log(Level.SEVERE, null, ex);
//                }
            

        }
    }//GEN-LAST:event_jTreeRoleValueChanged

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        DialogCreateRole createRole = new DialogCreateRole(null,true);
        createRole.setVisible(true);
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1ActionPerformed
        // Refresh
        loadTreeItems();
    }//GEN-LAST:event_btn_delete1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTreeRole;
    // End of variables declaration//GEN-END:variables
}
