/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.UserDao;
import DTO.UserDto;
import Product_Component.ProductModul;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Da Phadenphorakden
 */
public class RoleFrm extends javax.swing.JPanel {

    /**
     * Creates new form RoleFrm
     */
    UserDao dao = new UserDao();

    public RoleFrm() throws Exception {
        initComponents();
        this.jTable1.setCellSelectionEnabled(false);
        this.jTable1.setRowSelectionAllowed(true);
        List<UserDto> result = dao.loadUserRole();
        this.showUsers(result);
    }

    public void showUsers(List<UserDto> users) {
        //insert into jtable
        DefaultTableModel tbl = (DefaultTableModel) this.jTable1.getModel();
        tbl.setRowCount(0);//clear
        for (UserDto dto : users) {
            tbl.addRow(new Object[]{dto.getUid(), dto.getUname(), dto.getUpass(), dto.getRole_name()});
        }
        if (tbl.getRowCount() > 0) {
            this.jTable1.setRowSelectionInterval(0, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSetRole = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_permission = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_refresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btnSetRole.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btnSetRole.setText("Set Role");
        btnSetRole.setPreferredSize(new java.awt.Dimension(80, 28));
        btnSetRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetRoleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSetRole);
        jToolBar1.add(jSeparator2);

        btn_permission.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_permission.setText("Permission Detail");
        btn_permission.setFocusable(false);
        btn_permission.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_permission.setMaximumSize(new java.awt.Dimension(77, 28));
        btn_permission.setMinimumSize(new java.awt.Dimension(77, 28));
        btn_permission.setPreferredSize(new java.awt.Dimension(150, 28));
        btn_permission.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_permission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_permissionActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_permission);
        jToolBar1.add(jSeparator5);

        btn_refresh.setFont(new java.awt.Font("Geist Mono", 0, 14)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.setFocusable(false);
        btn_refresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_refresh.setMaximumSize(new java.awt.Dimension(77, 28));
        btn_refresh.setMinimumSize(new java.awt.Dimension(77, 28));
        btn_refresh.setPreferredSize(new java.awt.Dimension(90, 28));
        btn_refresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_refresh);

        jLabel1.setFont(new java.awt.Font("Geist Mono", 0, 48)); // NOI18N
        jLabel1.setText("ROLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Geist Mono", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UID", "User Name", "Password", "User Role"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetRoleActionPerformed
        // Set Role
        try {
            DefaultTableModel tbl = (DefaultTableModel) this.jTable1.getModel();
            if (tbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No record selected!");
                return;
            }
            int idx = this.jTable1.getSelectedRow();
            long user_id = dao.loadUserRole().get(idx).getUid();
            String user_name = dao.loadUserRole().get(idx).getUname();
            int role_id = dao.loadUserRole().get(idx).getRole_id();
            String role_name = dao.loadUserRole().get(idx).getRole_name();
            if (btnSetRole.getText().equals("Set Role")) {
                DialogSetRole setroleform = new DialogSetRole(null, user_id, user_name, role_id, role_name);
                if (idx == jTable1.getSelectedRow()) {
//                    System.out.println(user_id);
//                    System.out.println(user_name);
//                    System.out.println(role_id);
//                    System.out.println(role_name);
                    setroleform.setVisible(true);

                }

            }
        } catch (Exception e) {
            Logger.getLogger(RoleFrm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnSetRoleActionPerformed

    private void btn_permissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_permissionActionPerformed
         // Permission Detail
        try {
            DefaultTableModel tbl = (DefaultTableModel) this.jTable1.getModel();
            if (tbl.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No record selected!");
                return;
            }
            int idx = this.jTable1.getSelectedRow();
            String user_name = dao.loadUserRole().get(idx).getUname();
            int role_id = dao.loadUserRole().get(idx).getRole_id();
            if (btnSetRole.getText().equals("Set Role")) {
                DialogPermissionDetail setroleform = new DialogPermissionDetail(null, user_name, role_id);
                if (idx == jTable1.getSelectedRow()) {
//                    System.out.println(user_id);
//                    System.out.println(user_name);
//                    System.out.println(role_id);
//                    System.out.println(role_name);
                    setroleform.setVisible(true);

                }

            }
        } catch (Exception e) {
            Logger.getLogger(RoleFrm.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
    }//GEN-LAST:event_btn_permissionActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // Refresh
        List<UserDto> result = null;
        try {
            result = dao.loadUserRole();
        } catch (Exception ex) {
            Logger.getLogger(RoleFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        this.showUsers(result);
    }//GEN-LAST:event_btn_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetRole;
    private javax.swing.JButton btn_permission;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
